### ISSUE TITLE
Table 생성 건의

### ISSUE THREAD

**Issue by marunemo** [alsco1234/PP_Final#3]
* phpmyadmin에서 DB의 sql 탭에 이 SQL문 넣어주세요!
~~~
create table loginUser (
    sid int AUTO_INCREMENT,
    userid varchar(20),
    username varchar(40),
    password varchar(40),
    regdate timestamp default CURRENT_TIMESTAMP,
    primary key(sid)
)
~~~
* 그리고 되도록이면 main 브랜치 대신 **새로운 브랜치 생성해서 새로운 기능이 오류 없이 완성되었을 때**만 merge하는 방식으로 진행해주세요!

**Comment by alsco1234** [comment]
> 테이블 추가하였습니다.
> 확인했습니다. 실수했던 점 사과드립니다.

**Comment by marunemo** [comment]
> * 테이블 추가하였습니다.
> * 확인했습니다. 실수했던 점 사과드립니다.

감사합니다!
